server:
  port: 8088


spring:
  application:
    name: HealthCare-ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SuryaTejaYatam/HealthCare-ConfigServer
          clone-on-start: true